# Generated by Django 5.2.16 on 2026-08-15 14:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gallery", "0004_like"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("photo_like", "Photo like")],
                        db_index=True,
                        max_length=32,
                        verbose_name="Type",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Read"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "last_triggered_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Last triggered",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="gallery.photo",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-last_triggered_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "kind"],
                        name="notif_rec_read_kind_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "photo_like"), _negated=True),
                            models.Q(
                                ("actor__isnull", False), ("photo__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="photo_like_requires_actor_photo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "photo_like"), _negated=True),
                            models.Q(("recipient", models.F("actor")), _negated=True),
                            _connector="OR",
                        ),
                        name="photo_like_actor_not_recipient",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "photo_like")),
                        fields=("recipient", "actor", "kind", "photo"),
                        name="unique_photo_like_notification",
                    ),
                ],
            },
        ),
    ]
