# Generated by Django 5.2.16 on 2026-08-15 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_like"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="photo_like_requires_actor_photo",
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "photo_like"), _negated=True),
                    ("photo__isnull", False),
                    _connector="OR",
                ),
                name="photo_like_requires_photo",
            ),
        ),
    ]
