# Generated by Django 5.2.16 on 2026-08-15 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_like"),
        (
            "notifications",
            "0002_remove_notification_photo_like_requires_actor_photo_and_more",
        ),
        ("posts", "0003_alter_comment_options_alter_comment_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="posts.comment",
                verbose_name="Comment",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("photo_like", "Photo like"),
                    ("photo_comment", "Photo comment"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="Type",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "photo_comment"), _negated=True),
                    models.Q(("photo__isnull", False), ("comment__isnull", False)),
                    _connector="OR",
                ),
                name="photo_comment_requires_photo_comment",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "photo_comment"), _negated=True),
                    models.Q(("recipient", models.F("actor")), _negated=True),
                    _connector="OR",
                ),
                name="photo_comment_actor_not_recipient",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "photo_comment")),
                fields=("recipient", "actor", "kind", "comment"),
                name="unique_photo_comment_notification",
            ),
        ),
    ]
