# Generated by Django 5.2.16 on 2026-08-20 12:53

import django.db.models.deletion
import gallery.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")],
                        default="photo",
                        help_text="Media type stored in this album.",
                        max_length=10,
                        verbose_name="Album type",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("user", "User album"),
                            ("profile_photos", "Profile photos"),
                            ("post_photos", "Post photos"),
                        ],
                        db_index=True,
                        default="user",
                        help_text="Internal purpose of this album.",
                        max_length=32,
                        verbose_name="Purpose",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Album title.", max_length=100, verbose_name="Title"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique album identifier.",
                        max_length=120,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional album description.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends only"),
                            ("private", "Only me"),
                        ],
                        default="public",
                        help_text="Who can view this album.",
                        max_length=20,
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this album is visible.",
                        verbose_name="Visible",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galleries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo album",
                "verbose_name_plural": "Photo albums",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=gallery.models.photo_upload_path, verbose_name="Image"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional photo title.",
                        max_length=100,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional photo description.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this photo is visible.",
                        verbose_name="Visible",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="gallery.useralbum",
                        verbose_name="Album",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="gallery.photo",
                        verbose_name="Photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Like",
                "verbose_name_plural": "Likes",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "photo"), name="unique_user_photo_like"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="useralbum",
            constraint=models.UniqueConstraint(
                fields=("user", "slug"), name="unique_user_album_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="useralbum",
            constraint=models.UniqueConstraint(
                condition=models.Q(("purpose", "profile_photos")),
                fields=("user",),
                name="unique_profile_photos_album_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="useralbum",
            constraint=models.UniqueConstraint(
                condition=models.Q(("purpose", "post_photos")),
                fields=("user",),
                name="unique_post_photos_album_per_user",
            ),
        ),
    ]
