# Generated by Django 5.2.16 on 2026-08-11 06:58

import django.db.models.deletion
import gallery.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAlbum",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "album_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")],
                        default="photo",
                        help_text="Media type stored in this album.",
                        max_length=10,
                        verbose_name="Album type",
                    ),
                ),
                ("title", models.CharField(help_text="Album title.", max_length=100, verbose_name="Title")),
                ("slug", models.SlugField(help_text="Unique album identifier.", max_length=120, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional album description.", verbose_name="Description"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("friends", "Friends only"), ("private", "Only me")],
                        default="public",
                        help_text="Who can view this album.",
                        max_length=20,
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, help_text="Whether this album is visible.", verbose_name="Visible"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galleries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo album",
                "verbose_name_plural": "Photo albums",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to=gallery.models.photo_upload_path, verbose_name="Image")),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Optional photo title.", max_length=100, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional photo description.", verbose_name="Description"),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, help_text="Whether this photo is visible.", verbose_name="Visible"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="gallery.useralbum",
                        verbose_name="Album",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="useralbum",
            constraint=models.UniqueConstraint(fields=("user", "slug"), name="unique_user_album_slug"),
        ),
    ]
