# Generated by Django 5.2.16 on 2026-08-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="title",
        ),
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional photo caption.",
                max_length=150,
                verbose_name="Description",
            ),
        ),
    ]
