# Generated by Django 5.2.16 on 2026-08-11 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="useralbum",
            name="purpose",
            field=models.CharField(
                choices=[("user", "User album"), ("profile_photos", "Profile photos")],
                db_index=True,
                default="user",
                help_text="Internal purpose of this album.",
                max_length=32,
                verbose_name="Purpose",
            ),
        ),
        migrations.AddConstraint(
            model_name="useralbum",
            constraint=models.UniqueConstraint(
                condition=models.Q(("purpose", "profile_photos")),
                fields=("user",),
                name="unique_profile_photos_album_per_user",
            ),
        ),
    ]
