# Generated by Django 5.2.16 on 2026-08-12 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_useralbum_purpose_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="useralbum",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("user", "User album"),
                    ("profile_photos", "Profile photos"),
                    ("post_photos", "Post photos"),
                ],
                db_index=True,
                default="user",
                help_text="Internal purpose of this album.",
                max_length=32,
                verbose_name="Purpose",
            ),
        ),
        migrations.AddConstraint(
            model_name="useralbum",
            constraint=models.UniqueConstraint(
                condition=models.Q(("purpose", "post_photos")),
                fields=("user",),
                name="unique_post_photos_album_per_user",
            ),
        ),
    ]
