class BlockService:

    @staticmethod
    def block(user, target): ...

    @staticmethod
    def unblock(user, target): ...

    @staticmethod
    def can_send_message(user, target): ...

    @staticmethod
    def can_view_profile(user, target): ...

    @staticmethod
    def can_start_video_chat(user, target): ...

    @staticmethod
    def can_add_friend(user, target): ...

    @staticmethod
    def can_comment(user, target): ...

    @staticmethod
    def can_like(user, target): ...

    @staticmethod
    def can_visit_profile(user, target): ...

    @staticmethod
    def can_find_in_search(user, target): ...
