# Generated by Django 5.2.16 on 2026-08-05 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "dialog_type",
                    models.CharField(
                        choices=[("private", "Private"), ("group", "Group")],
                        db_index=True,
                        default="private",
                        max_length=20,
                        verbose_name="Dialog type",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="Title")),
                ("last_activity_at", models.DateTimeField(auto_now=True, db_index=True, verbose_name="Last activity")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_dialogs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dialog",
                "verbose_name_plural": "Dialogs",
                "ordering": ("-last_activity_at",),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(blank=True, verbose_name="Текст")),
                ("is_edited", models.BooleanField(default=False, verbose_name="Отредактировано")),
                ("edited_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата редактирования")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Удалено")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "dialog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messenger.dialog",
                        verbose_name="Диалог",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="messenger.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="dialog",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="messenger.message",
                verbose_name="Last message",
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="messenger/attachments/%Y/%m/", verbose_name="Файл")),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[("image", "Изображение"), ("video", "Видео"), ("file", "Файл"), ("audio", "Аудио")],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("original_name", models.CharField(max_length=255, verbose_name="Исходное имя файла")),
                ("file_size", models.PositiveBigIntegerField(verbose_name="Размер файла (байт)")),
                ("mime_type", models.CharField(blank=True, max_length=100, verbose_name="MIME-тип")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="messenger.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение",
                "verbose_name_plural": "Вложения",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_archived", models.BooleanField(default=False, verbose_name="Архивирован")),
                ("is_muted", models.BooleanField(default=False, verbose_name="Без уведомлений")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("joined_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата вступления")),
                (
                    "dialog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="messenger.dialog",
                        verbose_name="Диалог",
                    ),
                ),
                (
                    "last_read_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="messenger.message",
                        verbose_name="Последнее прочитанное сообщение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialog_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник диалога",
                "verbose_name_plural": "Участники диалогов",
                "ordering": ("id",),
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["dialog", "id"], name="messenger_m_dialog__8c76b0_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["dialog", "created_at"], name="messenger_m_dialog__59ea40_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["sender"], name="messenger_m_sender__9b25bf_idx"),
        ),
        migrations.AddIndex(
            model_name="dialog",
            index=models.Index(fields=["dialog_type"], name="messenger_d_dialog__9696aa_idx"),
        ),
        migrations.AddIndex(
            model_name="dialog",
            index=models.Index(fields=["-last_activity_at"], name="messenger_d_last_ac_c4085c_idx"),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(fields=["message"], name="messenger_a_message_926d3e_idx"),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(fields=["attachment_type"], name="messenger_a_attachm_4a5434_idx"),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(fields=["user"], name="messenger_p_user_id_48979f_idx"),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(fields=["dialog"], name="messenger_p_dialog__9bfc11_idx"),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(fields=("dialog", "user"), name="unique_dialog_participant"),
        ),
    ]
