# Generated by Django 5.2.16 on 2026-08-06 08:53

import messenger.models.dialog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialog",
            name="public_id",
            field=models.CharField(
                db_index=True,
                default=messenger.models.dialog.generate_public_id,
                editable=False,
                max_length=16,
                verbose_name="Public ID",
            ),
        ),
    ]
