# Generated by Django 5.2.16 on 2026-08-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0003_alter_dialog_public_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_deleted",
        ),
    ]
