# Generated by Django 5.2.16 on 2026-08-20 12:53

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.comparison
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("gallery", "0001_initial"),
        ("geo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.PositiveIntegerField()),
                ("days", models.PositiveIntegerField()),
                ("source", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_1", models.CharField(max_length=250)),
                ("data_2", models.CharField(max_length=250)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPremiumFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incognito_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Browse profiles without appearing in visitors lists.",
                    ),
                ),
                (
                    "anonymous_profile_views",
                    models.BooleanField(
                        default=False,
                        help_text="Hide profile visit activity from other users.",
                    ),
                ),
                (
                    "hide_online_status_from_everyone",
                    models.BooleanField(
                        default=False,
                        help_text="Completely hide online status from all users.",
                    ),
                ),
                (
                    "random_chat_gender_filter",
                    models.BooleanField(
                        default=False,
                        help_text="Enable gender filtering in random chat.",
                    ),
                ),
                (
                    "priority_matching",
                    models.BooleanField(
                        default=False, help_text="Prioritize matching with other users."
                    ),
                ),
                (
                    "advanced_search",
                    models.BooleanField(
                        default=False, help_text="Enable advanced search filters."
                    ),
                ),
                (
                    "unlimited_search_radius",
                    models.BooleanField(
                        default=False, help_text="Remove search distance limitations."
                    ),
                ),
                (
                    "hd_video",
                    models.BooleanField(
                        default=False, help_text="Enable high-definition video calls."
                    ),
                ),
                (
                    "unsend_messages",
                    models.BooleanField(
                        default=False,
                        help_text="Allow deleting messages after sending.",
                    ),
                ),
                (
                    "scheduled_messages",
                    models.BooleanField(
                        default=False,
                        help_text="Allow scheduling messages for future delivery.",
                    ),
                ),
                (
                    "extended_message_editing",
                    models.BooleanField(
                        default=False,
                        help_text="Extend the time limit for editing messages.",
                    ),
                ),
                (
                    "custom_profile_theme",
                    models.BooleanField(
                        default=False, help_text="Allow custom profile themes."
                    ),
                ),
                (
                    "animated_profile_badge",
                    models.BooleanField(
                        default=False,
                        help_text="Display an animated premium profile badge.",
                    ),
                ),
                (
                    "profile_accent_color",
                    models.BooleanField(
                        default=False, help_text="Allow custom profile accent colors."
                    ),
                ),
                (
                    "profile_statistics",
                    models.BooleanField(
                        default=False, help_text="Access detailed profile statistics."
                    ),
                ),
                (
                    "profile_visitors",
                    models.BooleanField(
                        default=False, help_text="See who visited your profile."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the premium feature set was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the premium feature set was last updated.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user who owns these premium features.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_features",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Premium Features",
                "verbose_name_plural": "User Premium Features",
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("friends", "Friends only"),
                            ("only_me", "Only me"),
                        ],
                        default="everyone",
                        help_text="Controls who can view the user's profile.",
                        max_length=16,
                    ),
                ),
                (
                    "friends_visibility",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("friends", "Friends only"),
                            ("only_me", "Only me"),
                        ],
                        default="everyone",
                        help_text="Controls who can view the friends list.",
                        max_length=16,
                    ),
                ),
                (
                    "photo_albums_visibility",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("friends", "Friends only"),
                            ("only_me", "Only me"),
                        ],
                        default="everyone",
                        help_text="Controls who can view photo albums.",
                        max_length=16,
                    ),
                ),
                (
                    "wall_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable the wall on the user's profile."
                    ),
                ),
                (
                    "show_online_status",
                    models.BooleanField(
                        default=True, help_text="Display online status to other users."
                    ),
                ),
                (
                    "blur_media",
                    models.BooleanField(
                        default=False,
                        help_text="Blur all images, avatars, videos, and other media across the site until you choose to reveal them.",
                    ),
                ),
                (
                    "message_permission",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("friends", "Friends only"),
                            ("only_me", "Only me"),
                        ],
                        default="everyone",
                        help_text="Controls who can send private messages.",
                        max_length=16,
                    ),
                ),
                (
                    "comments_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable comments on the user's content.",
                        verbose_name="Comments enabled",
                    ),
                ),
                (
                    "comment_permission",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("friends", "Friends only"),
                            ("only_me", "Only me"),
                        ],
                        default="everyone",
                        help_text="Controls who can leave comments.",
                        max_length=16,
                    ),
                ),
                (
                    "wall_post_permission",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("friends", "Friends only"),
                            ("only_me", "Only me"),
                        ],
                        default="everyone",
                        help_text="Controls who can publish posts on the user's wall.",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the settings were created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the settings were last updated.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user these settings belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "content_type", "object_id"),
                        name="unique_favorite",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted")],
                        default="pending",
                        help_text="Current status of the friendship relation.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the friend request was created.",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the friend request was accepted.",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the friendship relation was last updated.",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        help_text="The user who initiated the friendship request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_friendships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        help_text="The user who received the friendship request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friendships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Friendship",
                "verbose_name_plural": "Friendships",
                "indexes": [
                    models.Index(
                        fields=["from_user", "status"],
                        name="users_frien_from_us_9e7907_idx",
                    ),
                    models.Index(
                        fields=["to_user", "status"],
                        name="users_frien_to_user_db034b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.comparison.Least(
                            "from_user", "to_user"
                        ),
                        django.db.models.functions.comparison.Greatest(
                            "from_user", "to_user"
                        ),
                        name="unique_friendship_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_user", models.F("to_user")), _negated=True
                        ),
                        name="prevent_self_friendship",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["pending", "accepted"])),
                        name="valid_friendship_status",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the user's identity has been verified.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag. Deleted profiles remain in the database.",
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the profile has been banned by moderators.",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Unique Telegram user ID linked to this account.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "telegram_data",
                    models.JSONField(
                        blank=True,
                        help_text="Cached Telegram profile data received during authentication.",
                        null=True,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Short personal description displayed on the profile.",
                        max_length=500,
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        blank=True,
                        help_text="A short status displayed on your profile (up to 150 characters).",
                        max_length=150,
                        validators=[django.core.validators.MaxLengthValidator(150)],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("couple", "Couple"),
                            ("non_binary", "Non-binary"),
                        ],
                        help_text="User's gender or profile type.",
                        max_length=20,
                    ),
                ),
                (
                    "looking_for",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("male", "Male"),
                                ("female", "Female"),
                                ("couple", "Couple"),
                                ("non_binary", "Non-binary"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        help_text="Profiles the user is interested in meeting.",
                        size=None,
                    ),
                ),
                (
                    "open_to_gifts",
                    models.BooleanField(
                        default=False,
                        help_text="Open to dating where gifts or financial support may be part of the relationship.",
                    ),
                ),
                (
                    "financial_meetings_only",
                    models.BooleanField(
                        default=False,
                        help_text="The user is interested only in meetings on a financial basis.",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="User's date of birth.", null=True
                    ),
                ),
                (
                    "premium",
                    models.DateTimeField(
                        blank=True,
                        help_text="Premium subscription expiration date and time.",
                        null=True,
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Last recorded online activity.",
                    ),
                ),
                (
                    "profile_views",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of profile views."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the profile was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the profile was last updated.",
                    ),
                ),
                (
                    "avatar_photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected profile avatar.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="gallery.photo",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.city",
                        verbose_name="City",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.region",
                        verbose_name="Region",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user account associated with this profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["looking_for"], name="users_profi_looking_0aa6b3_gin"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfileVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visited_at",
                    models.DateTimeField(
                        help_text="Date and time of the most recent profile visit."
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="The owner of the visited profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_visits_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        help_text="The user who visited the profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_visits_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Visit",
                "verbose_name_plural": "Profile Visits",
                "indexes": [
                    models.Index(
                        fields=["profile", "-visited_at"],
                        name="profile_visit_profile_idx",
                    ),
                    models.Index(fields=["visitor"], name="profile_visit_visitor_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("visitor", "profile"), name="unique_profile_visit"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("visitor", models.F("profile")), _negated=True
                        ),
                        name="prevent_self_profile_visit",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Blocked user",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocking",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Block owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "User block",
                "verbose_name_plural": "User blocks",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["blocked"], name="users_userb_blocked_49cac4_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blocker", "blocked"), name="unique_user_block"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("blocker", models.F("blocked")), _negated=True
                        ),
                        name="prevent_self_block",
                    ),
                ],
            },
        ),
    ]
