# Generated by Django 5.2.16 on 2026-07-25 12:57

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.PositiveIntegerField()),
                ("days", models.PositiveIntegerField()),
                ("source", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")],
                        default="photo",
                        help_text="Media type stored in this album.",
                        max_length=10,
                        verbose_name="Album type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Album title.", max_length=100, verbose_name="Title"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique album identifier.",
                        max_length=120,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional album description.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("friends", "Friends only")],
                        default="public",
                        help_text="Who can view this album.",
                        max_length=20,
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this album is visible.",
                        verbose_name="Visible",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_albums",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo album",
                "verbose_name_plural": "Photo albums",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="...", verbose_name="Image")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional photo title.",
                        max_length=100,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional photo description.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this photo is visible.",
                        verbose_name="Visible",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="users.useralbum",
                        verbose_name="Album",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_1", models.CharField(max_length=250)),
                ("data_2", models.CharField(max_length=250)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPremiumFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incognito_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Browse profiles without appearing in visitors lists.",
                    ),
                ),
                (
                    "anonymous_profile_views",
                    models.BooleanField(
                        default=False,
                        help_text="Hide profile visit activity from other users.",
                    ),
                ),
                (
                    "hide_online_status_from_everyone",
                    models.BooleanField(
                        default=False,
                        help_text="Completely hide online status from all users.",
                    ),
                ),
                (
                    "random_chat_gender_filter",
                    models.BooleanField(
                        default=False,
                        help_text="Enable gender filtering in random chat.",
                    ),
                ),
                (
                    "random_chat_country_filter",
                    models.BooleanField(
                        default=False,
                        help_text="Enable country filtering in random chat.",
                    ),
                ),
                (
                    "random_chat_language_filter",
                    models.BooleanField(
                        default=False,
                        help_text="Enable language filtering in random chat.",
                    ),
                ),
                (
                    "random_chat_age_filter",
                    models.BooleanField(
                        default=False, help_text="Enable age filtering in random chat."
                    ),
                ),
                (
                    "priority_matching",
                    models.BooleanField(
                        default=False, help_text="Prioritize matching with other users."
                    ),
                ),
                (
                    "advanced_search",
                    models.BooleanField(
                        default=False, help_text="Enable advanced search filters."
                    ),
                ),
                (
                    "unlimited_search_radius",
                    models.BooleanField(
                        default=False, help_text="Remove search distance limitations."
                    ),
                ),
                (
                    "hd_video",
                    models.BooleanField(
                        default=False, help_text="Enable high-definition video calls."
                    ),
                ),
                (
                    "unsend_messages",
                    models.BooleanField(
                        default=False,
                        help_text="Allow deleting messages after sending.",
                    ),
                ),
                (
                    "scheduled_messages",
                    models.BooleanField(
                        default=False,
                        help_text="Allow scheduling messages for future delivery.",
                    ),
                ),
                (
                    "extended_message_editing",
                    models.BooleanField(
                        default=False,
                        help_text="Extend the time limit for editing messages.",
                    ),
                ),
                (
                    "custom_profile_theme",
                    models.BooleanField(
                        default=False, help_text="Allow custom profile themes."
                    ),
                ),
                (
                    "animated_profile_badge",
                    models.BooleanField(
                        default=False,
                        help_text="Display an animated premium profile badge.",
                    ),
                ),
                (
                    "profile_accent_color",
                    models.BooleanField(
                        default=False, help_text="Allow custom profile accent colors."
                    ),
                ),
                (
                    "profile_statistics",
                    models.BooleanField(
                        default=False, help_text="Access detailed profile statistics."
                    ),
                ),
                (
                    "profile_visitors",
                    models.BooleanField(
                        default=False, help_text="See who visited your profile."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the premium feature set was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the premium feature set was last updated.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user who owns these premium features.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_features",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Premium Features",
                "verbose_name_plural": "User Premium Features",
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        help_text="Controls who can view the user's profile.",
                        max_length=16,
                    ),
                ),
                (
                    "show_online_status",
                    models.BooleanField(
                        default=True, help_text="Display online status to other users."
                    ),
                ),
                (
                    "friends_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        help_text="Controls who can view the friends list.",
                        max_length=16,
                    ),
                ),
                (
                    "photo_albums_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        help_text="Controls who can view photo albums.",
                        max_length=16,
                    ),
                ),
                (
                    "private_message_permission",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("friends", "Friends only"),
                            ("nobody", "Nobody"),
                        ],
                        default="everyone",
                        help_text="Controls who can send private messages.",
                        max_length=16,
                    ),
                ),
                (
                    "comment_permission",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("friends", "Friends only"),
                            ("nobody", "Nobody"),
                        ],
                        default="everyone",
                        help_text="Controls who can leave comments.",
                        max_length=16,
                    ),
                ),
                (
                    "wall_post_permission",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("friends", "Friends only"),
                            ("nobody", "Nobody"),
                        ],
                        default="friends",
                        help_text="Controls who can publish posts on the user's wall.",
                        max_length=16,
                    ),
                ),
                (
                    "notify_messages",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications about new messages.",
                    ),
                ),
                (
                    "notify_friend_requests",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications about friend requests.",
                    ),
                ),
                (
                    "notify_email",
                    models.BooleanField(
                        default=False,
                        help_text="Receive important notifications by email.",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ru", "Russian"),
                            ("uk", "Ukrainian"),
                        ],
                        default="en",
                        help_text="Preferred interface language.",
                        max_length=2,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the settings were created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the settings were last updated.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user these settings belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        help_text="Current status of the friendship request.",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the friendship request was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the friendship request was last updated.",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        help_text="The user who initiated the friendship request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        help_text="The user who received the friendship request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Friendship",
                "verbose_name_plural": "Friendships",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_user", "to_user"),
                        name="unique_friendship_request",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_user", models.F("to_user")), _negated=True
                        ),
                        name="prevent_self_friendship",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the user's identity has been verified.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete flag. Deleted profiles remain in the database.",
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the profile has been banned by moderators.",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Unique Telegram user ID linked to this account.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "telegram_data",
                    models.JSONField(
                        blank=True,
                        help_text="Cached Telegram profile data received during authentication.",
                        null=True,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Short personal description displayed on the profile.",
                        max_length=500,
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        blank=True,
                        help_text="A short status displayed on your profile (up to 150 characters).",
                        max_length=150,
                        validators=[django.core.validators.MaxLengthValidator(150)],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("couple", "Couple"),
                            ("non_binary", "Non-binary"),
                        ],
                        help_text="User's gender or profile type.",
                        max_length=20,
                    ),
                ),
                (
                    "looking_for",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("male", "Male"),
                                ("female", "Female"),
                                ("couple", "Couple"),
                                ("non_binary", "Non-binary"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        help_text="Profiles the user is interested in meeting.",
                        size=None,
                    ),
                ),
                ("birth_date", models.DateField(help_text="User's date of birth.")),
                (
                    "premium",
                    models.DateTimeField(
                        blank=True,
                        help_text="Premium subscription expiration date and time.",
                        null=True,
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Last recorded online activity.",
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Current online status."
                    ),
                ),
                (
                    "profile_views",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of profile views."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the profile was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the profile was last updated.",
                    ),
                ),
                (
                    "avatar_photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected profile avatar.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.photo",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.city",
                        verbose_name="City",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geo.region",
                        verbose_name="Region",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user account associated with this profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["looking_for"], name="users_profi_looking_0aa6b3_gin"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfileVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visited_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time of the most recent profile visit.",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="The owner of the visited profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_visits_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        help_text="The user who visited the profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_visits_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Visit",
                "verbose_name_plural": "Profile Visits",
                "indexes": [
                    models.Index(
                        fields=["profile", "-visited_at"],
                        name="users_profi_profile_936359_idx",
                    ),
                    models.Index(
                        fields=["visitor"], name="users_profi_visitor_d98c36_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("visitor", "profile"), name="unique_profile_visit"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("visitor", models.F("profile")), _negated=True
                        ),
                        name="prevent_self_profile_visit",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="useralbum",
            constraint=models.UniqueConstraint(
                fields=("user", "slug"), name="unique_user_album_slug"
            ),
        ),
    ]
