# Generated by Django 5.2.16 on 2026-07-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(
                blank=True, help_text="User's date of birth.", null=True
            ),
        ),
    ]
