# Generated by Django 5.2.16 on 2026-08-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="comments_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable comments on the user's content.",
                verbose_name="Comments enabled",
            ),
        ),
    ]
