# Generated by Django 5.2.16 on 2026-07-26 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_birth_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersettings",
            old_name="private_message_permission",
            new_name="message_permission",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_online",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="notify_email",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="notify_friend_requests",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="notify_messages",
        ),
        migrations.AddField(
            model_name="profile",
            name="open_to_gifts",
            field=models.BooleanField(
                default=False,
                help_text="Open to dating where gifts or financial support may be part of the relationship.",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="wall_enabled",
            field=models.BooleanField(default=True, help_text="Enable the wall on the user's profile."),
        ),
        migrations.AlterField(
            model_name="useralbum",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galleries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
