# Generated by Django 5.2.16 on 2026-08-14 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usersettings_comments_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="friendship",
            name="users_frien_to_user_76f00a_idx",
        ),
        migrations.AddField(
            model_name="friendship",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the friend request was accepted.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the friend request was created.",
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted")],
                default="pending",
                help_text="Current status of the friendship relation.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the friendship relation was last updated.",
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "accepted"])),
                name="valid_friendship_status",
            ),
        ),
    ]
