# Generated by Django 5.2.16 on 2026-07-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_private_message_permission_usersettings_message_permission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="blur_sensitive",
            field=models.BooleanField(
                default=False, help_text="Blur images and media marked as sensitive until you choose to reveal them."
            ),
        ),
    ]
