# Generated by Django 5.2.16 on 2026-07-28 07:21

import users.models.gallery
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_usersettings_blur_sensitive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to=users.models.gallery.photo_upload_path, verbose_name="Image"),
        ),
    ]
