# Generated by Django 5.2.16 on 2026-07-28 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_photo_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="from_user",
            field=models.ForeignKey(
                help_text="The user who initiated the friendship request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiated_friendships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted")],
                default="pending",
                help_text="Current status of the friendship request.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="to_user",
            field=models.ForeignKey(
                help_text="The user who received the friendship request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_friendships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(fields=["to_user"], name="users_frien_to_user_76f00a_idx"),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(fields=["from_user", "status"], name="users_frien_from_us_9e7907_idx"),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(fields=["to_user", "status"], name="users_frien_to_user_db034b_idx"),
        ),
    ]
