# Generated by Django 5.2.16 on 2026-07-30 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_favorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Blocked user",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocking",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Block owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "User block",
                "verbose_name_plural": "User blocks",
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["blocked"], name="users_userb_blocked_49cac4_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("blocker", "blocked"), name="unique_user_block"),
                    models.CheckConstraint(
                        condition=models.Q(("blocker", models.F("blocked")), _negated=True), name="prevent_self_block"
                    ),
                ],
            },
        ),
    ]
