# Generated by Django 5.2.16 on 2026-08-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_userblock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="blur_sensitive",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="blur_media",
            field=models.BooleanField(
                default=False,
                help_text="Blur all images, avatars, videos, and other media across the site until you choose to reveal them.",
            ),
        ),
    ]
