# Generated by Django 5.2.16 on 2026-08-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_usersettings_blur_sensitive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="financial_meetings_only",
            field=models.BooleanField(
                default=False, help_text="The user is interested only in meetings on a financial basis."
            ),
        ),
    ]
