# Generated by Django 5.2.16 on 2026-08-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_profile_financial_meetings_only"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="profilevisit",
            new_name="profile_visit_profile_idx",
            old_name="users_profi_profile_936359_idx",
        ),
        migrations.RenameIndex(
            model_name="profilevisit",
            new_name="profile_visit_visitor_idx",
            old_name="users_profi_visitor_d98c36_idx",
        ),
        migrations.RemoveField(
            model_name="userpremiumfeatures",
            name="random_chat_age_filter",
        ),
        migrations.RemoveField(
            model_name="userpremiumfeatures",
            name="random_chat_country_filter",
        ),
        migrations.RemoveField(
            model_name="userpremiumfeatures",
            name="random_chat_language_filter",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="language",
        ),
        migrations.AlterField(
            model_name="profilevisit",
            name="visited_at",
            field=models.DateTimeField(help_text="Date and time of the most recent profile visit."),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="comment_permission",
            field=models.CharField(
                choices=[("everyone", "Everyone"), ("friends", "Friends only"), ("only_me", "Only me")],
                default="everyone",
                help_text="Controls who can leave comments.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="friends_visibility",
            field=models.CharField(
                choices=[("everyone", "Everyone"), ("friends", "Friends only"), ("only_me", "Only me")],
                default="everyone",
                help_text="Controls who can view the friends list.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="message_permission",
            field=models.CharField(
                choices=[("everyone", "Everyone"), ("friends", "Friends only"), ("only_me", "Only me")],
                default="everyone",
                help_text="Controls who can send private messages.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="photo_albums_visibility",
            field=models.CharField(
                choices=[("everyone", "Everyone"), ("friends", "Friends only"), ("only_me", "Only me")],
                default="everyone",
                help_text="Controls who can view photo albums.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="profile_visibility",
            field=models.CharField(
                choices=[("everyone", "Everyone"), ("friends", "Friends only"), ("only_me", "Only me")],
                default="everyone",
                help_text="Controls who can view the user's profile.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="wall_post_permission",
            field=models.CharField(
                choices=[("everyone", "Everyone"), ("friends", "Friends only"), ("only_me", "Only me")],
                default="everyone",
                help_text="Controls who can publish posts on the user's wall.",
                max_length=16,
            ),
        ),
    ]
