# Generated by Django 5.2.16 on 2026-08-11 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("geoname_id", models.IntegerField(db_index=True, unique=True)),
                ("name_en", models.CharField(max_length=200)),
                ("name_uk", models.CharField(blank=True, max_length=200)),
                ("name_ru", models.CharField(blank=True, max_length=200)),
                (
                    "code2",
                    models.CharField(db_index=True, max_length=2, unique=True, verbose_name="ISO 3166-1 alpha-2"),
                ),
                ("code3", models.CharField(blank=True, max_length=3, verbose_name="ISO 3166-1 alpha-3")),
                ("continent", models.CharField(blank=True, max_length=2)),
                ("phone_code", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name_en"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("geoname_id", models.IntegerField(db_index=True, unique=True)),
                ("name_en", models.CharField(max_length=200)),
                ("name_uk", models.CharField(blank=True, max_length=200)),
                ("name_ru", models.CharField(blank=True, max_length=200)),
                ("geoname_code", models.CharField(blank=True, db_index=True, max_length=20)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="regions", to="geo.country"
                    ),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["name_en"],
                "unique_together": {("country", "geoname_code")},
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("geoname_id", models.IntegerField(db_index=True, unique=True)),
                ("name_en", models.CharField(max_length=200)),
                ("name_uk", models.CharField(blank=True, max_length=200)),
                ("name_ru", models.CharField(blank=True, max_length=200)),
                ("population", models.IntegerField(db_index=True, default=0)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("feature_code", models.CharField(blank=True, max_length=10)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cities", to="geo.country"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cities",
                        to="geo.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["-population", "name_en"],
                "indexes": [
                    models.Index(fields=["country", "-population"], name="geo_city_country_3998f8_idx"),
                    models.Index(fields=["region", "-population"], name="geo_city_region__09b4eb_idx"),
                    models.Index(fields=["name_en"], name="geo_city_name_en_09002f_idx"),
                    models.Index(fields=["name_uk"], name="geo_city_name_uk_69cce8_idx"),
                    models.Index(fields=["name_ru"], name="geo_city_name_ru_bc3880_idx"),
                ],
            },
        ),
    ]
