# Generated by Django 5.2.16 on 2026-08-12 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_alter_useralbum_purpose_and_more"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_media_items",
                        to="gallery.photo",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
                "indexes": [
                    models.Index(
                        fields=["post", "position"], name="post_media_position_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "photo"), name="unique_photo_per_post"
                    )
                ],
            },
        ),
    ]
