# Generated by Django 5.2.16 on 2026-08-13 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_alter_useralbum_purpose_and_more"),
        ("posts", "0002_postmedia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("created_at", "id")},
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "created_at"], name="comment_post_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["photo", "created_at"], name="comment_photo_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent", "created_at"], name="comment_parent_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("post__isnull", False), ("photo__isnull", True)),
                    models.Q(("post__isnull", True), ("photo__isnull", False)),
                    _connector="OR",
                ),
                name="comment_exactly_one_target",
            ),
        ),
    ]
