# Generated by Django 5.2.16 on 2026-08-11 06:58

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        help_text="Unique internal identifier used in code and queries.",
                        max_length=255,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("site_page", "Site Page"),
                            ("academy", "Academy"),
                            ("content", "Content"),
                            ("json", "JSON Data"),
                        ],
                        db_index=True,
                        default="content",
                        help_text="Determines which section of the site this record belongs to.",
                        max_length=20,
                        verbose_name="Content type",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="SEO-friendly URL slug. Usually generated from the key.",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable or disable this content on the site.", verbose_name="Is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
            ],
            options={
                "verbose_name": "Content",
                "verbose_name_plural": "Content",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="ContentLocale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ru", "Russian"), ("uk", "Ukrainian")], default="en", max_length=2
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HTML TAB title. Recommended: up to 60 characters.",
                        max_length=255,
                        verbose_name="Page title",
                    ),
                ),
                (
                    "content_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="H1 heading displayed on the page.",
                        max_length=255,
                        verbose_name="Content title",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short summary used in cards and previews.",
                        verbose_name="Short description",
                    ),
                ),
                (
                    "plain_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Plain text without HTML formatting.",
                        verbose_name="Plain text",
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(
                        blank=True,
                        default="",
                        help_text="Main HTML content edited with TinyMCE.",
                        verbose_name="Content",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="SEO meta description tag head. Recommended: up to 160 characters.",
                        verbose_name="Meta description",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Structured JSON data for this language version.",
                        null=True,
                        verbose_name="JSON data",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable or disable this language version.", verbose_name="Is active"
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        help_text="Parent content record.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locales",
                        to="cms.content",
                        verbose_name="Relation content key",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content locale",
                "verbose_name_plural": "Content locales",
                "ordering": ["language"],
                "constraints": [
                    models.UniqueConstraint(fields=("content_item", "language"), name="unique_content_locale")
                ],
            },
        ),
    ]
